version: "3.7"

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ../volumes/database/postgres-data:/var/lib/postgresql/data # to keep the database data persistent
    env_file:
      - ./.env.dev

  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 app:app
    # for debugging using vscode
    # command: python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./services/web/:/usr/src/
      - ../volumes/database/assets:/assets
    expose:
      - 5000
    ports:
      - 5678:5678
    env_file:
      - ./.env.dev
    depends_on:
      - db

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
      - ./logs/letsencrypt:/var/log/letsencrypt/
    command: certonly --webroot -w /var/www/certbot --force-renewal --email "steven@perga.app" -d "app-server.perga.app" --agree-tos

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    depends_on:
      - web
      - certbot
  
  helloworld:
    container_name: helloworld
    image: crccheck/hello-world
    expose:
      - 8000
